{{ HTML::script('assets/js/jquery.min.js') }}
{{ HTML::script('assets/js/bootstrap.min.js') }}
{{ HTML::script('assets/js/twitter-bootstrap-hover-dropdown.min.js') }}
{{ HTML::script('assets/js/retina.js') }}
{{ HTML::script('assets/js/jquery.slickforms.js') }}
{{ HTML::script('assets/js/jquery.animsition.min.js') }}
{{ HTML::script('assets/js/isotope.pkgd.min.js') }}
{{ HTML::script('assets/js/owl.carousel.min.js') }}
{{ HTML::script('assets/js/instafeed.min.js') }}
{{ HTML::script('assets/js/jquery.easytabs.min.js') }}
{{ HTML::script('assets/js/fotorama.js') }}
{{ HTML::script('assets/js/idangerous.swiper.min.js') }}
{{ HTML::script('assets/js/jquery.fancybox.pack.js') }}
{{ HTML::script('assets/js/fancybox/helpers/jquery.fancybox-thumbs.js?v=1.0.2') }}
{{ HTML::script('assets/js/fancybox/helpers/jquery.fancybox-media.js?v=1.0.0') }}
{{ HTML::script('assets/js/jquery.fitvids.js') }}
{{ HTML::script('assets/js/jquery.themepunch.revolution.min.js') }}
{{ HTML::script('assets/js/jquery.themepunch.tools.min.js') }}
{{ HTML::script('assets/js/jquery.divas-1.0.min.js') }}
{{ HTML::script('assets/js/imagesloaded.pkgd.min.js') }}
{{ HTML::script('assets/js/scripts.js') }}